services:
  app:
    container_name: app
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 15s
      retries: 3
    volumes:
      - ./volumes/redis_data:/data
    networks:
      - app-network

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:

volumes:
  redis_data: